server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb
    datasource:
      url: jdbc:mysql://localhost:3060/demotesting
      username: root
      password: glorzo
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
